"""renamed columns

Revision ID: 6487bfd4c8aa
Revises: 8c08809abb09
Create Date: 2018-08-09 15:54:28.683879

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '6487bfd4c8aa'
down_revision = '8c08809abb09'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('labs', sa.Column('reportDate', sa.Date(), nullable=True))
    op.add_column('labs', sa.Column('reportTime', sa.Time(), nullable=True))
    op.alter_column('labs', 'recvDate',
               existing_type=sa.DATE(),
               nullable=False)
    op.alter_column('labs', 'recvTime',
               existing_type=postgresql.TIME(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('labs', 'recvTime',
               existing_type=postgresql.TIME(),
               nullable=True)
    op.alter_column('labs', 'recvDate',
               existing_type=sa.DATE(),
               nullable=True)
    op.drop_column('labs', 'reportTime')
    op.drop_column('labs', 'reportDate')
    # ### end Alembic commands ###
