"""added foreign key to the labs

Revision ID: 8c08809abb09
Revises: e581a3205c91
Create Date: 2018-08-09 15:53:04.835590

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8c08809abb09'
down_revision = 'e581a3205c91'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('labs', sa.Column('order_id', sa.String(length=16), nullable=True))
    op.create_foreign_key(None, 'labs', 'orders', ['order_id'], ['orderId'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'labs', type_='foreignkey')
    op.drop_column('labs', 'order_id')
    # ### end Alembic commands ###
