"""added test, order, lab, and relationships

Revision ID: c5494b14736d
Revises: e219034e79ac
Create Date: 2018-08-09 15:39:47.278149

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c5494b14736d'
down_revision = 'e219034e79ac'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('orders',
    sa.Column('orderId', sa.String(length=16), nullable=False),
    sa.Column('orderDate', sa.Date(), nullable=False),
    sa.Column('orderTime', sa.Time(), nullable=False),
    sa.Column('doctor', sa.String(length=128), nullable=True),
    sa.PrimaryKeyConstraint('orderId')
    )
    op.create_table('tests',
    sa.Column('testCode', sa.String(length=8), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('unit', sa.String(length=16), nullable=True),
    sa.PrimaryKeyConstraint('testCode')
    )
    op.create_table('labs',
    sa.Column('labId', sa.String(length=16), nullable=False),
    sa.Column('test_id', sa.String(length=16), nullable=True),
    sa.Column('recvDate', sa.Date(), nullable=True),
    sa.Column('recvTime', sa.Time(), nullable=True),
    sa.Column('results', sa.Numeric(), nullable=True),
    sa.ForeignKeyConstraint(['test_id'], ['tests.testCode'], ),
    sa.PrimaryKeyConstraint('labId')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('labs')
    op.drop_table('tests')
    op.drop_table('orders')
    # ### end Alembic commands ###
