"""replaced column names with snakecase

Revision ID: cf22dec470bc
Revises: 6487bfd4c8aa
Create Date: 2018-08-09 17:19:24.101500

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'cf22dec470bc'
down_revision = '6487bfd4c8aa'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('patients', 'firstName', new_column_name='first_name')
    op.alter_column('patients', 'lastName', new_column_name='last_name')
    op.alter_column('tests', 'testCode', new_column_name='test_code')
    op.alter_column('labs', 'reportTime', new_column_name='report_time')
    op.alter_column('labs', 'recvDate', new_column_name='recv_date')
    op.alter_column('labs', 'recvTime', new_column_name='recv_time')
    op.alter_column('labs', 'labId', new_column_name='lab_id')
    op.alter_column('labs', 'reportDate', new_column_name='report_date')
    op.alter_column('orders', 'orderDate', new_column_name='order_date')
    op.alter_column('orders', 'orderId', new_column_name='order_id')
    op.alter_column('orders', 'orderTime', new_column_name='order_time')
    op.drop_constraint('labs_test_id_fkey', 'labs', type_='foreignkey')
    op.drop_constraint('labs_order_id_fkey', 'labs', type_='foreignkey')
    op.create_foreign_key(None, 'labs', 'orders', ['order_id'], ['order_id'])
    op.create_foreign_key(None, 'labs', 'tests', ['test_id'], ['test_code'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('tests', 'test_code', new_column_name='testCode')
    op.alter_column('patients', 'last_name', new_column_name='lastName')
    op.alter_column('patients', 'first_name', new_column_name='firstName')
    op.alter_column('orders', 'order_time', new_column_name='orderTime')
    op.alter_column('orders', 'order_id', new_column_name='orderId')
    op.alter_column('orders', 'order_date', new_column_name='orderDate')
    op.drop_constraint(None, 'labs', type_='foreignkey')
    op.drop_constraint(None, 'labs', type_='foreignkey')
    op.create_foreign_key('labs_order_id_fkey', 'labs', 'orders', ['order_id'], ['orderId'])
    op.create_foreign_key('labs_test_id_fkey', 'labs', 'tests', ['test_id'], ['testCode'])
    op.alter_column('labs', 'report_time', new_column_name='reportTime')
    op.alter_column('labs', 'report_date', new_column_name='reportDate')
    op.alter_column('labs', 'recv_time', new_column_name='recvTime')
    op.alter_column('labs', 'recv_date', new_column_name='recvDate')
    op.alter_column('labs', 'lab_id', new_column_name='labId')
    # ### end Alembic commands ###
