"""initial revision

Revision ID: e219034e79ac
Revises: 
Create Date: 2018-08-09 08:23:07.266531

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e219034e79ac'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('patients',
                    sa.Column('id', sa.String(length=16), nullable=False),
                    sa.Column('firstName', sa.String(length=128), nullable=True),
                    sa.Column('lastName', sa.String(length=128), nullable=True),
                    sa.Column('email', sa.String(length=128), nullable=True),
                    sa.Column('gender', sa.String(length=8), nullable=True),
                    sa.Column('birthdate', sa.Date(), nullable=False),
                    sa.PrimaryKeyConstraint('id')
                    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('patients')
    # ### end Alembic commands ###
