"""added foreign key to the orders

Revision ID: e581a3205c91
Revises: c5494b14736d
Create Date: 2018-08-09 15:51:47.022650

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e581a3205c91'
down_revision = 'c5494b14736d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orders', sa.Column('patient_id', sa.String(length=16), nullable=True))
    op.create_foreign_key(None, 'orders', 'patients', ['patient_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'orders', type_='foreignkey')
    op.drop_column('orders', 'patient_id')
    # ### end Alembic commands ###
